version: '3.1'

services:
   db:
     image: mysql:5.7
     volumes:
       - ./mysql:/var/lib/mysql
     restart: always
     networks:
       - privnet
     environment:
       MYSQL_DATABASE: classicmodels
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
   wordpress:
     depends_on:
       - db
     build: 
        context: ./wordpress
        args:
           WPVERSION: 5.4.0-php7.2-apache
     ports:
       - 80:80
       - 443:443
     restart: always
     networks:
       - pubnet
     healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost"]
        interval: 1m30s
        timeout: 10s
        retries: 3
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wp123456
       WORDPRESS_DB_NAME: wordpress
volumes:
   mysql: {}
networks:
   pubnet:
     external: true
   privnet: 
     external: false
